### ISSUE TITLE
Gracefully fail if there are no credentials

### ISSUE THREAD

**Issue by andreasciamanna** [typical-organization/param-store-service#5]
I'm trying to use this package (thanks for it!) for what is meant to be used: to retrieve secrets.

However, to simplify the life of some contributors, I need to allow falling back to an `.env` (git-ignored) for local development, when the developer does not have the right credentials.

It would be great if the service could return an empty array when it can't connect to SSM.
I'm ok also if I need to set a specific property or an environment variable to disable it.

Would that be possible?

**Comment by parikmaan** [comment]
As of v2.0.1 application will continue and will receive an empty array if there is an issue fetching properties from AWS parameter store.
